config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'home', to: 'static_pages#home', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show, :edit, :update]

  match '/users',         to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',    via: 'get'

  resources :chat_rooms, only: [:new, :create, :show, :index]

  mount ActionCable.server => '/cable'

  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  def timestamp
    created_at.strftime('%B %d, %Y at %H:%M')
  end
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%B %d, %Y at %H:%M')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # parameters to allow username in devise
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:paradigm, :quote, :book, :age, :first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:paradigm, :quote, :book, :age, :first_name, :last_name, :username, :email, :password, :remember_me) }
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @chat_rooms = ChatRoom.all.order(created_at: :desc)
  end

  def new
    @chat_room = ChatRoom.new

    question_array = ["Why is there something rather than nothing?", "Could we possibly be living in a computer simulation?", "What are colors?", "Is there progress in philosophy?", "Is science compatible with religion?",
                      "Is love just a feeling?", "What is the sound of one hand clapping?", "If the only thing I know is that I know nothing, do I know something?", "Is morality relative?", "Does truth exist?",
                      "If you could live forever, would you?", "If someone offered to tell you exactly what would happen in 20 years, but you would be powerless to change what they tell you, would you want to hear it?",
                      "Which would you rather be - an unhappy human being or a happy dog?", "Are emotions irrational?", "Is it always better to have more choices?", "What is art?", "Is democracy the same as decision by the majority?",
                      "Are numbers real? What is a number?", "Are there parallel universes?", "If you can travel back in time, can you kill your earlier self?", "Is time travel possible?", "Can we be absolutely certain of anything?",
                      "Is mathematics the same as logic?", "Does every event have a cause?", "Are you your body or your mind?", "Can wars ever be just?", "Are you the same person you were ten years ago?", "Why do we dream?",
                      "Can something be at two places at the same time?", "If you go back in time and teach young Einstein relativity theory, where does the idea come from?", "Does every event have a cause?", "How do you know you are not dreaming right now?",
                      "If we live in a computer simulation, does it make a difference to the meaning of life?", "If meat can be grown using stem cells, is there any reason not to eat meat?", "Is it the main purpose of law to promote morality?",
                      "What is friendship and why do we need it?", "If there is no freewill, should we punish people at all?", "Does freewill really exist?"]

    @new_question = question_array.sample
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :question)
  end
end

app/controllers/message_controller.rb
class MessagesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :authenticate_user!
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    quotes_array = ["'The fact that everybody in the world dreams every night ties all mankind together.'  -Jack Kerouac", "'Trying to define yourself is like trying to bite your own teeth.'  -Alan Watts",
                    "'Technology is destructive only in the hands of people who do not realize that they are one and the same process as the universe.'  -Alan Watts", "'You are precisely as big as what you love and precisely as small as what you allow to annoy you.'  -Robert Anton Wilson",
                    "Only the madman is absolutely sure.  -Robert Anton Wilson", "'A secret is not something untold. It’s something which can’t be told.'  -Terence McKenna", "The flame that burns Twice as bright burns half as long.  -Lao Tzu",
                    "'The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.'  -Friedrich Nietsche", "Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend. -Albert Camus",
                    "'Blessed are the hearts that can bend; they shall never be broken' -Albert Camus", "'Reality is only a Rorschach ink-blot, you know.' -Alan Watts", "'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.'  -Rumi",
                    "'Even After All this time The Sun never says to the Earth, 'You owe me.' Look What happens With a love like that, It lights the whole sky.' -Hafez", "'Metaphysics is a dark ocean without shores or lighthouse, strewn with many a philosophic wreck'  -Immanuel Kant",
                    "'Man is condemned to be free'  -Jean-Paul Sartre", "'Freedom is secured not by the fulfilling of one's desires, but by the removal of desire'  -Epicetus", "'Everything that exists is born for no reason, carries on living through weakness, and dies by accident'  -Jean-Paul Sartre",
                    "'I would never die for my beliefs because I might be wrong'  -Bertrand Russel", "'We are what we repeatedly do. Excellence, then, is not an act, but a habit' -Aristotle", "'He who thinks great thoughts, often makes great errors'  -Martin Heidegger"]

    @thought = quotes_array.sample
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:id])
  end

  def index
    @users = User.all.order(username: :asc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://media.creativemornings.com/uploads/user/avatar/6930/small_avatar.jpg",
              opts
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/_chat_room.html.erb
<div class="well chat-single"><%= link_to "#{chat_room.title}- #{chat_room.question}", chat_room_path(chat_room), class:'room' %></div>

app/views/chat_rooms/index.html.erb
<body id="bg5">
    <div class="well chat-index">
        <h1 class="new-title">
            <strong>Let's have a chat</strong>
        </h1>
        <p class="lead"><%= link_to 'Create a new DeepChat', new_chat_room_path, class: 'btn btn-primary' %></p>
    </div>

    <div>
        <%= render @chat_rooms %>
    </div>

</body>

app/views/chat_rooms/new.html.erb
<body id="bg6">
    <div class="well chat-index">
        <strong><h1 class="new-title">Create a new DeepChat</h1></strong>
        <p class="description">
          Create a new chat with the suggested question, or come up with one of your own! Refresh the page to generate a new question.
        </p>
        <%= form_for @chat_room do |f| %>
        <div class="form-group">
            <strong><%= f.label :subject %></strong>
            <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
            <strong><%= f.label :question %></strong>
            <%= f.text_field :question, :value => "#{@new_question}",autofocus: true, class: 'form-control' %>
        </div>
        <%= f.submit "Create chat!", class: 'btn btn-primary' %>
        <% end %>
    </body>
</div>

app/views/chat_rooms/show.html.erb
<body id="bg4">
    <div class="well" id="chat-container">
        <h1 class="description"><%= @chat_room.title %></h1>

        <div id="question-container">
            <h3 class="question">Discussion Question: </h3>
            <h5 class="question"><%= @chat_room.question %></h5>
        </div>

        <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
            <%= render @chat_room.messages %>
        </div>

        <hr>

        <%= form_for @message, url: '#' do |f| %>
        <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
        <div class="form-group">
            <%= f.label :message %>
            <%= f.text_area :body, class: 'form-control' %>
            <small class="text-muted">2-1000 characters</small>
        </div>

        <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
        <% end %>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>DeepChats</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Averia+Serif+Libre" rel="stylesheet">
    </head>

    <body>

        <nav class="navbar navbar-dark bg-inverse">
            <strong><%= link_to 'DeepChats', root_path, class: 'navbar-brand' %></strong>
            <%= link_to 'About', '/about', class: 'navbar-brand left-nav-items' %>
            <%= link_to 'Chat', chat_rooms_path, class: 'navbar-brand left-nav-items' %>
            <% if user_signed_in? %>
            <ul class="nav navbar-nav pull-xs-right">
                <li class="nav-item nav-link">
                    <span class="text-muted">Logged in as
                        <strong><%= current_user.username %></strong>
                    </span>
                </li>
                <li class="nav-item active">
                    <%= link_to 'My Profile', user_path(current_user.username), class: 'nav-link' %>
                </li>
                <li class="nav-item active">
                    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
            </ul>
        <% else %>
            <ul class="nav navbar-nav pull-xs-right">
                <li class="nav-item active"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
                <li class="nav-item active"><%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
            </ul>
            <% end %>
        </nav>

        <div class="container">
            <%= yield %>
        </div>

        <footer>
            <div class="container">
                <p class="text-muted">
                    <!--footer here-->
                </p>
            </div>
        </footer>
    </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
        <p class="card-text">
          <strong class="username"><%= message.user.username %>:</strong>
          <%= message.body %>
          <!--at <%= message.timestamp %> <br />-->
        </p>
  </div>
</div>

app/views/static_pages/about.html.erb
<body id="bg3">
  <div class="well profile description">
<% provide(:title, 'About') %>
<h1>DeepChats: A chat application for deep conversation</h1>
<h4>Made by Sam Mershon with:</h4>
<ul id="tech">
  <li><a href="https://www.ruby-lang.org/">Ruby 2.3</a></li>
  <li><a href="http://rubyonrails.org/">Rails 5.0</a></li>
  <li><a href="http://www.postgresql.org/">PostgreSQL 9.5</a></li>
  <li><a href="http://getbootstrap.com/">Twitter Bootstrap 3.3</a></li>
  <li><a href="http://sass-lang.com/">SASS 3.4</a></li>
  <li><a href="http://redis.io/">Redis 3.2</a></li>
  <li><a href="https://www.poetryfoundation.org/love-poems">And lots of love 💖</a></li>
</ul>
</div>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<html>
    <body id="bg2">
        <div id="home">
            <div class="jumbotron">
                <h1 id="title">Welcome to DeepChats</h1>
                <h3 id="sub">Where contemplation meets conversation</h3>
                <div id="authBtns">
                  <% if signed_in? %>
                    <div id="enter-chat">
                      <%= link_to "Join a chat now!", chat_rooms_path, class: "btn btn-xlarge" %>
                    </div>
                  <% else %>
                  <div id="new">
                    <%= link_to "Register", new_user_registration_path, class: "btn btn-xlarge unauth" %>
                    <%= link_to "Log in",  new_user_session_path,      class: "btn btn-xlarge unauth" %>
                  </div>
                  <% end %>
                </div>
            </div>
        </div>
        <div class="well food">
          <h4>Food for thought:</h4>
            <h5 id="thought"><%= @thought %></h5>
        </div>
    </body>
</html>

app/views/users/index.html.erb
<body id="bg3">
  <div class="well profile description">
    <h1 class="user-list">User List</h1>
    <h3 class="user-list">Meet your fellow philosophers!</h3>
  </div>
  <br/>
  <div id="users">
    <% @users.each do |user| %>
      <div class="well" id="user">
        <li>
          <strong><%= user.username %></strong>
          <%= link_to '- View Profile', user_path(user.username) %>
        </li>
      </div>
      <br/>
  </div>
    <% end %>
</body>

app/views/users/show.html.erb
<body id="bg2">
    <div class="well profile">
        <h1 class="new-title"><%= @user.username %></h1>
        
        <h4>Name:
            <span class="profileInfo"><%= @user.first_name %>
                <%= @user.last_name %></span>
        </h4>
        <h4>Email:
            <span class="profileInfo"><%= @user.email %></span>
        </h4>
        <h4>Age:
            <span class="profileInfo"><%= @user.age %></span>
        </h4>
        <h4>Philosophy:
            <span class="profileInfo"><%= @user.paradigm %></span>
        </h4>
        <h4>Favorite Quote:
            <span class="profileInfo"><%= @user.quote %></span>
        </h4>
        <h4>Favorite Book:
            <span class="profileInfo"><%= @user.book %></span>
        </h4>
        <br/>
        <div class="profileBtns">
            <%= link_to 'Edit My Profile', edit_user_registration_path, class: 'btn btn-primary prof' %>
            <%= link_to 'View all profiles', users_path, class: 'btn btn-primary prof' %>
        </div>
    </div>
</body>